contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #manticore channel"
    url: https://nfcore.slack.com/channels/manticore
    about: Discussion about the nf-core/manticore pipeline
